### ISSUE TITLE
After zoom out: Set the image in the center of the parent container

### ISSUE THREAD

**Issue by 13Aks13** [manuelstofer/pinchzoom#100]
How can I set the image in the center of the parent container after zoom out will be done?

**Comment by sandstrom** [comment]
Is this an issue with the code itself, or a general question? For general questions [Stackoverflow](https://stackoverflow.com/) is better than Github.

I'm closing this now, but I'm willing to reopen if there is an actual code issue. If so, steps to reproduce (and ideally a failing test-case) is a good start.
