### ISSUE TITLE
PinchZoom.js not working on iOS devices after 13.4 update by Apple

### ISSUE THREAD

**Issue by rahsharm77** [manuelstofer/pinchzoom#111]
Hello,

So I have run into a problem with this plugin which started happening after the 13.4 update by Apple for iOS devices. The problem is that the double tap feature has suddenly stopped working completely on iOS devices now.

For a concrete test, you can refer to the plugin demo page: http://manuelstofer.github.io/pinchzoom/demo/pinchzoom.html

On iOS devices, you won't be able to double tap to zoom in the image whereas this was working fine in previous versions of iOS. I have even dived down in the source code of the plugin but I am not sure what is causing the double tap TO NOT work in iOS devices after the update.

If anyone has any idea/workaround for this, it would be very helpful.

Thanks

**Comment by GaryG54** [comment]
The demo is version 2.2.0, while the current release is 2.3.4.   Also note, it's been changed to an ES6 module.  You'll have to port it for JS for use like the demo.

**Comment by sandstrom** [comment]
@rahsharm77 Great if you (as Gary says) can try with the most recent version.

Also, happy to update the demo if anyone wants to submit a PR.

**Comment by rahsharm77** [comment]
@GaryG54 @sandstrom Thank you for the clarification on the demo but unfortunately I am using the Version: 2.3.4 of pinchzoom in my site and this problem is also happening there. You can take a look at this question that I posted on S.O:

https://stackoverflow.com/questions/62072906/pinchzoom-js-not-working-on-ios-devices-after-13-4-update-by-apple

Thanks,
R.S

**Comment by sandstrom** [comment]
Since this code is open-source, without anyone getting paid to work on it, it's difficult to satisfy all the wishes that people may have. I hope you understand! 🌻 

Would you like to work on a PR to fix this issue?

**Comment by rahsharm77** [comment]
@sandstrom I totally understand that point and I would be more than glad to help on this and hopefully fix the issue. I will start investigating deeper on this.

**Comment by sandstrom** [comment]
@rahsharm77 much appreciated!

A much larger (but also possible) approach would be to rewrite the lib to use pointer events:
https://github.com/manuelstofer/pinchzoom/issues/114

(but happy to accept a small patch fixing this issue too)

**Comment by sandstrom** [comment]
Did the solution proposed on StackOverflow solve your issue?

https://stackoverflow.com/questions/62072906/pinchzoom-js-not-working-on-ios-devices-after-13-4-update-by-apple

Do you think that fix is applicable only to your circumstances, or is that something we should change in this project?

Also, do you know if that proposed solution causes any issues on Android?

**Comment by rahsharm77** [comment]
The fix in that answer resolved the zoom issue but caused other problems in scrolling and clicking on links on the website so I had to revert back unfortunately and not use that solution. 

The fix is not applicable to my circumstance but I am not exactly sure how will it affect other scenarios. In my case, I was having problems in the over scrolling of the image and I was not able to click on icons placed over the image so there are side effects of this fix and I would not suggest it. I will also try to give you a working example with the fix and without the fix so that you can see it for yourself.

**Comment by rahsharm77** [comment]
Please check these two links on your mobile/tablet devices and see the behaviour:

1) Without the fix: **https://eetts.avahan.co.in/Home/Index**
2) With the fix: **https://epapertest.eenadu.net/Home/Index?date=27/10/2020&eid=3&pid=1178597**

You will experience problems in scrolling in the second link.
Hope this helps.

**Comment by sandstrom** [comment]
thanks for the update @rahsharm77

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? I'll close now, but happy to reopen if this is still a problem.

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by GaryG54** [comment]
I found the code didn't work except in some simple cases.  I abandoned it.
