### ISSUE TITLE
How to install pinchzoom?

### ISSUE THREAD

**Issue by JiangWeian** [manuelstofer/pinchzoom#118]
When I execute npm install, an error will be reported:

> pinch-zoom-js@2.3.4 build H:\WORK\pinchzoom-2.3.4
> script/ build.sh

'script 'is not an internal or external command or a runnable program
Or batch file.

Do I need to install something to execute build.sh?

**Comment by sandstrom** [comment]
Is this an issue with the code itself, or a general question? For general questions [Stackoverflow](https://stackoverflow.com/) is better than Github.

I'm closing this now, but I'm willing to reopen if there is an actual code issue. If so, steps to reproduce (and ideally a failing test-case) is a good start.
