### ISSUE TITLE
Wrong homepage link

### ISSUE THREAD

**Issue by Hocdoc** [manuelstofer/pinchzoom#144]
The GitHub homepage link http://manuelstofer.github.com/pinchzoom/ doesn't work (Error 404).

**Comment by sandstrom** [comment]
If you PR a fix I'll merge.

**Comment by Hocdoc** [comment]
No PR possible, since this is in the GitHub project settings.
As a project admin just click on the settings icon right to the "About" box in GitHub and remove the Website.

**Comment by sandstrom** [comment]
Got it!

If you'd like to fix the Github Pages branch, I'd welcome a PR. But I don't have time to fix the broken site, or figure out why it's broken. Sorry!

Since this code is open-source, without anyone getting paid to work on it, it's difficult to fix all the bugs myself. I hope you understand! 🌻

**Comment by Hocdoc** [comment]
I understand that, but the link also isn't stored in the GitHub pages:

![Screenshot](https://github.com/manuelstofer/pinchzoom/assets/3492813/9bc213b9-b0b2-4182-997e-de7fc0c058db)

I mean the blue link http://manuelstofer.github.com/pinchzoom/ from the screenshot, you can just remove it in the GitHub project settings. 

Anyway, this isn't a big thing just a wrong link so if you don't have time for the fix it doesn't lower the quality of the project.

**Comment by sandstrom** [comment]
I don't have repo access, I cannot update that link.

I'm not the original author of this repo, merely someone who's been helping out with some maintenance. 

Looking forward though, I think this package would either need a large rewrite based on pointer events (the new framework for touch), or it's current users will gradually phase it out in favor of some other touch library, based on pointer events.

**Comment by Hocdoc** [comment]
Ok, thanks for the information and your effort.
