### ISSUE TITLE
How to enable Scroll 

### ISSUE THREAD

**Issue by cubarabara** [manuelstofer/pinchzoom#145]
how to enable scroll horizontal or vertical?

**Comment by sandstrom** [comment]
Is this an issue with the code itself, or a general question? For general questions [Stackoverflow](https://stackoverflow.com/) or [Github Discussions](https://docs.github.com/en/discussions) (if one is setup for this repo) is better than Github.

I'm closing this now, but I'm willing to reopen if there is an actual code issue. If so, steps to reproduce (and ideally a failing test-case) is a good start.
