### ISSUE TITLE
mousewheel -> wheel event rename

### ISSUE THREAD

**Issue by bobmagicii** [manuelstofer/pinchzoom#155]
pinch-zoom.js line 973 `el.addEventListener("mousewheel", function (event) {`

needs to be `wheel` instead of `mousewheel` - had to update our copy to make it work.

![image](https://github.com/user-attachments/assets/09393061-9237-41c8-bf94-818d0dc998a5)

**Comment by sandstrom** [comment]
I would accept a PR

**Comment by bobmagicii** [comment]
ok i've actually been at this for quite a while.

```
    2024-10-14 - bob
    * rename deprecated mouse wheel event.
    * passive mouse wheel event flag.

    2024-10-15 - bob
    * add onReady callback to instantiate options.
    * customize mouse wheel sensitivity
```

but the way i am doing this is by directly editing the pinch-zoom.js since that was the file that worked as an es6 module without driving me crazy, so i know very little about the js ecosystem yet alone your preferences for format and where i really should have made the edits to be built in for various module formats.
