### ISSUE TITLE
IE 10 Support

### ISSUE THREAD

**Issue by blairvanderhoof** [manuelstofer/pinchzoom#2]
IE 10 requires binding to different events for touchstart, touchmove, and touchend.  It also does not contain the touches property on the event object.
http://blogs.windows.com/windows_phone/b/wpdev/archive/2012/11/15/adapting-your-webkit-optimized-site-for-internet-explorer-10.aspx

**Comment by krisdigital** [comment]
@angelarted Sorry the Readme is not updated, I did not make a demo page.

**Comment by sandstrom** [comment]
@blairvanderhoof Sorry to let this linger.

Unfortunately IE 10 has a dwindling market share, especially on touch devices. So I'm going to close this.
