### ISSUE TITLE
Combine pinchzoom with tilezoom

### ISSUE THREAD

**Issue by elEglon** [manuelstofer/pinchzoom#22]
I read that pinchzoom can be combined with other libraries (swipe.js example). I tried to combine it with tilezoom (https://github.com/ematsakov/tilezoom). Because of my weak programming skills I was not able to realise the combination. Perhaps one of you is interested in combining the libraries to or is able to give a hint?

Thanks in advance

elEglon

**Comment by sandstrom** [comment]
If you are willing to open a PR and explain the use-case, and if accepted for further review you can write the code to make it work, I'm happy to have a look and offer some help.

Otherwise this may be a better fit for StackOverflow.
