### ISSUE TITLE
Rotate and drag on single fingure

### ISSUE THREAD

**Issue by suchg** [manuelstofer/pinchzoom#25]
Hi

I want to have Rotate, drag by single finger and pinch zoom by tow fingers. 
This plugin dose not support pinch zoom only, is it possible for you to support above mentioned things as well ?.

**Comment by manuelstofer** [comment]
Probably it is possible. Pull request is welcome.

**Comment by suchg** [comment]
Can you send any example for rotate, drag and pinch zoom all together.

**Comment by manuelstofer** [comment]
Pinchzoom does not support rotation yet. If you find a way to combine it with an other rotation library please create a pull request to document it with an example. Otherwise you can also integrate it into this library and create a pull request.
