### ISSUE TITLE
On drag image zoom in

### ISSUE THREAD

**Issue by csshore** [manuelstofer/pinchzoom#28]
I have used this code and it works fine.
But I face issue when one image make zoom in then do slide or next to get next image and on that image when we drag it goes in zoom in.
Is there any suggestion?
Thanks :)

**Comment by sandstrom** [comment]
Can you explain the issue in more detail? Preferably with some code illustrating the issue (js-fiddle).

**Comment by sandstrom** [comment]
I'm closing this now, but I'm willing to reopen if you can describe the issue in more detail (preferably with a test-case illustrating the issue).
