### ISSUE TITLE
How to use zoomOutAnimation()

### ISSUE THREAD

**Issue by brunodeleo** [manuelstofer/pinchzoom#29]
Hi, I love your plugin.
I currently need to use **zoomOutAnimation()** like mentioned in #16 but I can't seem to figure out how.
I tried using it on the jQuery element, but i get the _'is not a function'_ error:
`$('.zoom-element').zoomOutAnimation()`
Do I need to access the PinchZoom object? How would I do that after it was created?

Thanks in advance :)

**Comment by ahmadtout** [comment]
+1

**Comment by ahmadtout** [comment]
IMG =  new RTP.PinchZoom($("#img"), {});
IMG.zoomOutAnimation()

and it will work

**Comment by sandstrom** [comment]
I'll close this issue since ahmadtout has provided an answer.
