### ISSUE TITLE
How to tell if zoomed in or not?

### ISSUE THREAD

**Issue by brunodeleo** [manuelstofer/pinchzoom#30]
I'm currently trying to add a class to the body when PinchZoom is zoomed in and remove it when it's back in original scale.
I managed to listen to the **zoom start** event, but **zoom end** doesn't seem to trigger when on original scale, I'm not sure when **zoom end** triggers.
Also with the **double tap** event I can't tell if I'm zooming in or out.
So, is there a way to get the current or targeted zoom factor (or any other way) so I can tell if the image is zoomed in or not?

Thanks a lot.

**Comment by sandstrom** [comment]
Not currently. Listening to zoom end events should work, can you show a jsfiddle where it doesn't?

I agree with double-tap, it's ambiguous. It would be neat if the zoom-events + double-tap event contained a property called `zoom`, which contained the current zoom-level.

I don't have time to fix this myself, but will happily review a PR if you'd like to take a stab at it!

Will close this issue for now.
