### ISSUE TITLE
Can bind zoom to click, dbclick,...on PC

### ISSUE THREAD

**Issue by tthanhlong** [manuelstofer/pinchzoom#31]
It seems work well on device, but I want to bind zoom function to click, dbclick,... in PC web. I tried to override pinchzoom.js but not successful. Does anyone give me some advice.
Thanks and regards!

**Comment by sandstrom** [comment]
This library is focused on touch-devices. It's currently not possible to do what you desire.

What we could do is expose `pz.zoomIn(factor)` as a method. If you'd like to submit a PR I'm happy to review it (if you do, start with describing the API, so we can discuss it before you begin with the implementation).

I'm going to close this issue though, but again, happy to review a PR.

**Comment by NePheus** [comment]
`var $zc = $('.zoom-container');
var pz = <any> new RTP.PinchZoom($zc, { minZoom: .9, maxZoom: 2 });
$zc.on('click', function(e) {
    pz.handleDoubleTap({ touches: [{ pageX: (<any> e.originalEvent).pageX, pageY: (<any> e.originalEvent).pageY }] });
});`

**Comment by williammustaffa** [comment]
A way to do that is to extend the PinchZoom class:
```
    // Get container's center
    PinchZoom.prototype.getContainerCenter = function () {
      var centerX = this.container.offsetLeft + this.container.offsetWidth / 2;
      var centerY = this.container.offsetTop + this.container.offsetHeight / 2;

      return {
        x: centerX,
        y: centerY,
      };
    };

    // Create method to zoom to target zoom factor
    PinchZoom.prototype.zoomTo = function (zoomFactor) {
      var center = this.getContainerCenter();
      var startZoomFactor = this.zoomFactor;
      var updateProgress = (function (progress) {
        this.scaleTo(startZoomFactor + progress * (zoomFactor - startZoomFactor), center);
      }).bind(this);

      this.animate(this.options.animationDuration, updateProgress, this.swing);
    }
```
and use

```
pz.zoomTo(2); // zoom factor
```
