### ISSUE TITLE
Add information about browser compatibility

### ISSUE THREAD

**Issue by julmot** [manuelstofer/pinchzoom#37]
into README.md

**Comment by julmot** [comment]
Yes, please specify browsers and browser versions as you can't expect from users that they will look into the code and check every feature on the compat table.

**Comment by sandstrom** [comment]
Would you like to PR?

**Comment by julmot** [comment]
Nope, you'd have to test with many browsers and I don't have the time for that.

**Comment by sandstrom** [comment]
Alright, I appreciate the feedback but I'll close this issue then. I think ES5 is an adequate description of browser requirements.
