### ISSUE TITLE
Smooth pinching/dragging

### ISSUE THREAD

**Issue by julmot** [manuelstofer/pinchzoom#39]
If the target element isn't an image like demonstrated, the events won't be smooth. I've tested this with 10 KB `lorem ipsum` test content.

**Comment by sandstrom** [comment]
I think the library is mostly used for images. Do you have any thoughts on how this can be improved?

**Comment by julmot** [comment]
Yes, please document this in the docs. Mention something like "This library only works good for images".

**Comment by sandstrom** [comment]
Would you like to PR?

**Comment by sandstrom** [comment]
Closing this for now. Happy to re-open if anyone want to work on this!
