### ISSUE TITLE
Can't zoom to the bottom.

### ISSUE THREAD

**Issue by JedatKinports** [manuelstofer/pinchzoom#41]
I'm using this plugin for zooming images. I have a HTML DIV element and inside there are multiple images, normally 3-4.

My problem: when i zoom-in the first image (at the top) and then try to scroll to the bottom of the last image. I can't scroll to the bottom when zoomed in (the scrolling stops on 1/4 of the last image). If i zoom-out then i can scroll to the bottom again.

This happens only when there are multiple HTML IMG element inside the HTML DIV element. If there is only one image then everything works fine.

Any idea why this is happening or how i could make this work? Or how to use this when you have multiple images on the same html page?

**Comment by sandstrom** [comment]
@JedatKinports Can you provide a JS-fiddle that illustrate this problem? Cannot guarantee that I can help, but that would be a good start.

**Comment by sandstrom** [comment]
Closing this issue because it's stale. Happy to re-open if new information is provided.
