### ISSUE TITLE
How to unlock drag axis and also how to set default scaling value on load?

### ISSUE THREAD

**Issue by ShakeelBeyondvision** [manuelstofer/pinchzoom#48]
I am trying to unlock drag axis because of mobile screen and also scale problem how can I set default value and max and min value of scaling?

**Comment by sandstrom** [comment]
Is this an issue with the code, or a general question? For general questions sites like Stackoverflow are better.

I'm closing this now, but I'm willing to reopen if there is an actual code issue. If so you need to describe it much better.
