### ISSUE TITLE
Add inertia/momentum on drag scrolling?

### ISSUE THREAD

**Issue by beeant** [manuelstofer/pinchzoom#5]
Thank you for this library.

The drag scrolling doesn't feel so natural.
As I've seen through the codes, inertial drag scrolling seems to be not yet implemented.
Any plan to add inertial/momentum scrolling?

something like this
http://ariya.github.io/kinetic/2/

**Comment by antoniobrandao** [comment]
+ 1

**Comment by PickJBennett** [comment]
Yes from me too!

**Comment by unstableair** [comment]
I'd also appreciate this enhancement if possible :)

**Comment by manuelstofer** [comment]
pull request please :)

**Comment by sandstrom** [comment]
I'm going to close this issue. But will happily review a pull request implementing inertia, I think it would be a good addition.
