### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by danilowoz** [manuelstofer/pinchzoom#50]
Good job @manuelstofer!
Could you please publish as a npm package?

**Comment by sandstrom** [comment]
How would you recommend doing it? Webpack?

I know there are a few different methods, curious to hear if you have any thoughts on how to best go about it.

**Comment by danilowoz** [comment]
There are some boilerplate to publish, for example [npm-package-boilerplate](https://github.com/Danilo-Araujo-Silva/npm-package-boilerplate) and [boilerplate-npm-package](https://github.com/gyss/boilerplate-npm-package)

And [here](https://hackernoon.com/how-to-publish-your-package-on-npm-7fc1f5aae600) you can read a good article how use `npm publish`.

If you have another question, fell free to call me 😄

**Comment by sandstrom** [comment]
I'll see what I can do!

**Comment by sandstrom** [comment]
@danilowoz Can you try this one out? https://www.npmjs.com/package/pinch-zoom-js
