### ISSUE TITLE
does this support to zoom jquery-seats-charts? 

### ISSUE THREAD

**Issue by YGLau** [manuelstofer/pinchzoom#51]
i had used [jQuery-Seat-Charts](https://github.com/mateuszmarkowski/jQuery-Seat-Charts) to make a seat chart and want to zoom in/out it, but when first load this page, this charts was zoomed in, how can i fix this problem please?

**Comment by sandstrom** [comment]
If this is an open question it's better suited for Stackoverflow. I suggest you repost there.

If this is an issue with the source-code of pinch-zoom, please explain further and I'm happy to reopen.
