### ISSUE TITLE
Can you give me some annotation for getCurrentZoomCenter function？I donnot understand.Thanks

### ISSUE THREAD

**Issue by raferXu** [manuelstofer/pinchzoom#54]
getCurrentZoomCenter: function () {

      // uses following formula to calculate the zoom center x value
      // offset_left / offset_right = zoomcenter_x / (container_x - zoomcenter_x)
      var length = this.container.offsetWidth * this.zoomFactor,
        offsetLeft  = this.offset.x,
        offsetRight = length - offsetLeft - this.container.offsetWidth,
        widthOffsetRatio = offsetLeft / offsetRight,
        centerX = widthOffsetRatio * this.container.offsetWidth / (widthOffsetRatio + 1),

        // the same for the zoomcenter y
        height = this.container.offsetHeight * this.zoomFactor,
        offsetTop  = this.offset.y,
        offsetBottom = height - offsetTop - this.container.offsetHeight,
        heightOffsetRatio = offsetTop / offsetBottom,
        centerY = heightOffsetRatio * this.container.offsetHeight / (heightOffsetRatio + 1);

      // prevents division by zero
      if (offsetRight === 0) { centerX = this.container.offsetWidth; }
      if (offsetBottom === 0) { centerY = this.container.offsetHeight; }

      return {
        x: centerX,
        y: centerY
      };
    },

**Comment by sandstrom** [comment]
This looks like a general question. For those, [StackOverflow](https://stackoverflow.com) is a better place.

If you have found a real issue with this code a PR with a fix, or at least a failing test-case is a better start. I'm going to close this issue.
