### ISSUE TITLE
Double Tap from mobile devices

### ISSUE THREAD

**Issue by HuuDuc** [manuelstofer/pinchzoom#56]
Hi, I encounter an issue while I double tape in my touch screen to zoomIn or zoomOut. The precision is not accurate on touch screen. However it does work well once I double click from the "remote device" debugger.

**Comment by sandstrom** [comment]
Which git revision are you running under? How did you install the library?

**Comment by sandstrom** [comment]
Closing this issue because it's stale. Happy to re-open if new information is provided.
