### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by Garavani** [manuelstofer/pinchzoom#58]
Such a nice plugin. But I can’t get it to work.
Loading down the pinch zoom-master and trying the demo various error occur.
First: the filename seems to be wrong: 
In the html the line is: <script type="text/javascript" src="../src/pinchzoom.js"></script>
In the folder the name of the file actually is: pinch-zoom.js
Changing this line to: script type="text/javascript" src="../src/pinch-zoom.js"></script> then
new errors occur:
SyntaxError: Unexpected keyword 'export'
ReferenceError: Can't find variable: PinchZoom

**Comment by sandstrom** [comment]
@Garavani try running the build script, and point the demo to the built file.

I agree we should fix the demo, any suggestions on how?

Which browser are you running under?

**Comment by Garavani** [comment]
Hi Manuel,

thanks for getting in contact! Appreciate that!

Yes, I tried with the other code (copied from here: http://manuelstofer.github.io/pinchzoom/src/pinchzoom.js <http://manuelstofer.github.io/pinchzoom/src/pinchzoom.js>), too.
Adding also the jQuery link missing in the header of the demo html as it seems.

Browser (Safari latest) throws following errors then:

ReferenceError: Can't find variable: _
ReferenceError: Can't find variable: PinchZoom

Same in Firefox (latest)

Thanks for help!

Stefan
—

Stefan Seifert  ·  stefanseifert.com <http://stefanseifert.com/>  ·  @stefanseifert33 <https://twitter.com/stefanseifert33>

**Comment by Garavani** [comment]
PS
I also tested it mobile (http://www.seifertalbers.de/pinchzoom-master/demo/pinchzoom.html <http://www.seifertalbers.de/pinchzoom-master/demo/pinchzoom.html>)
In case it might work even with the errors.
But does not. 

thanks
Stefan

—

Stefan Seifert  ·  stefanseifert.com <http://stefanseifert.com/>  ·  @stefanseifert33 <https://twitter.com/stefanseifert33>

**Comment by Garavani** [comment]
Ok, I think I got it to work.
Copying literally all resources from your online demo.

The demo to download has wrong html, js files and it misses the underscore dependency.

Best
Stefan

—

Stefan Seifert  ·  stefanseifert.com <http://stefanseifert.com/>  ·  @stefanseifert33 <https://twitter.com/stefanseifert33>

**Comment by poebrand** [comment]
@sandstrom: the releases changed after v2.0.0. Both v2.0.1 and v2.1.0 contain pinch-zoom.js instead of pinchzoom.js. It also ends with an export statement that is not ECMA 5 compliant (statement is ECMA 6).

```
var PinchZoom = definePinchZoom();
export default PinchZoom;
```

It appears that we need to install babel in order to build based upon build.sh, is that right? Can you provide some guidance? Or should v2.0.1 and v2.1.0 not be publicly used?

**Comment by poebrand** [comment]
After some experimentation the steps for building appears to be:

1. Download release/source.
2. Download and install node.js
3. Extract the folder.
4. In my case, edit package.json and update build path to be explicit. Example: "build": "C:\\Users\\Admin\\Downloads\\pinchzoom-2.1.0\\script\\build.sh"
5. Open a command prompt and run: npm install
6. Should generate a dist folder at the root that contains: pinch-zoom.umd.js 

However, after that the standard initialization does not work:
```
let el = document.querySelector('#my-id');
let pz = new PinchZoom(el, options);
```

I had to do: 
```
let el = document.querySelector('#my-id');
var pz = new PinchZoom.default(el, {});
```

After that though, the following errors came up: 

> pinch-zoom.umd.js?d=20180402_224026:603 Uncaught TypeError: Cannot read property 'insertBefore' of undefined
>     at PinchZoom.setupMarkup (pinch-zoom.umd.js?d=20180402_224026:603)
>     at new PinchZoom (pinch-zoom.umd.js?d=20180402_224026:121)
>     at initZoom (productImageSlider.j…=20180402_224742:75)
>     at HTMLImageElement.<anonymous> (productImageSlider.j…20180402_224742:155)
>     at Function.each (ScriptResource.axd?d…=ffffffffd99926d3:2)
>     at e.fn.init.each (ScriptResource.axd?d…=ffffffffd99926d3:2)
>     at HTMLDocument.<anonymous> (productImageSlider.j…20180402_224742:153)
>     at i (ScriptResource.axd?d…=ffffffffd99926d3:2)
>     at Object.fireWith [as resolveWith] (ScriptResource.axd?d…=ffffffffd99926d3:2)
>     at Function.ready (ScriptResource.axd?d…=ffffffffd99926d3:2)

It appears that the project's documentation needs updating or that versions after 2.0.0 are not ready for use. Can you please update the project's documentation or provide some guidance?

**Comment by sandstrom** [comment]
Good discussion, some thoughts!

1. We should update the hosted demo (http://manuelstofer.github.io), not sure if I have permissions to do it, but I'll check.

2. Would like to keep ES6 modules for the source code, but need to figure out a way to make it work with browsers. There is `<script type='module' …>` but it requires CORS, so we'd need a way to serve the demo page from a local dev-server. Something like [local-web-server](https://www.npmjs.com/package/local-web-server) might work. Thoughts on this?

3. Another alternative is to use rollup/babel/browserify/etc to turn the ES6 code into something a browser can consume. 

4. I would like to avoid checking in the build artifacts (dist) unless there is no other way.

5. Agree that the file path for current demos is unaligned (pinchzoom.js vs. pinch-zoom.js).

Thoughts on this?

**Comment by poebrand** [comment]
The readme/documentation also needs an update. https://github.com/manuelstofer/pinchzoom

**Comment by sandstrom** [comment]
@poebrand Feel free to PR 😄

**Comment by sandstrom** [comment]
No response, closing this PR. Happy to reopen if the issue remains.
