### ISSUE TITLE
DOM events are slow

### ISSUE THREAD

**Issue by endel** [manuelstofer/pinchzoom#59]
I'm using a fork of this library, and I would like to let you guys know I've improved the performance quite a bit by replacing the [DOM event triggers](https://github.com/manuelstofer/pinchzoom/blob/8efa64c4775957e405d36064aa8c9e74058b25d1/src/pinch-zoom.js#L69-L73) with [`eventemitter3`](https://www.npmjs.com/package/eventemitter3).

**Comment by sandstrom** [comment]
@endel Interesting! 🏅 

- Do you know which underlying functionality is driving the performance improvement?
- Do you have any performance numbers? (before/after, and on which spec/machine)

I'm reluctant to add dependencies, but would be happy to accept a PR adjusting the current event generation code.

If browser support is good enough, perhaps a switch to `new Event('myEvent')` would yield similar performance improvements. Something you'd like to look into?
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events
