### ISSUE TITLE
canDrag is gone, doesn't interop with swipe.js anymore

### ISSUE THREAD

**Issue by tvler** [manuelstofer/pinchzoom#61]
Every touchmove event is now cancelled, even if an element isn't being zoomed.

This prevents pinchzoom elements from being used in swipe.js, or any other touchmove-based gallery library.

https://github.com/manuelstofer/pinchzoom/commit/7df8532828534d89b8d9c71061008c9471f7c710#diff-74f10427165b674d4d8a5c4bf321d992L450

**Comment by zyniq82** [comment]
@tvler I noticed this regression too!
I've issued a pull request to mitigate the issue :relieved:

**Comment by sandstrom** [comment]
@tvler Would https://github.com/manuelstofer/pinchzoom/pull/62 solve your issue?

**Comment by tvler** [comment]
Awesome, thanks!

**Comment by sandstrom** [comment]
@tvler A new release with @zyniq82's code is out now https://github.com/manuelstofer/pinchzoom/tree/v2.2.0

**Comment by tvler** [comment]
Great! Thanks for all your work on this project @sandstrom & @zyniq82, much appreciated at [openlistings](https://www.openlistings.com/) ;)
