### ISSUE TITLE
EventListeners should be removed on disable.

### ISSUE THREAD

**Issue by nimishsinghal** [manuelstofer/pinchzoom#63]
Hi,
Update is getting bind to image(when the image is loaded) which should be ideally unbinded once the image is removed or the disable event is triggered.

**Comment by nimishsinghal** [comment]
Thanks @sandstrom for a quick reply, will create a PR for this. In my case update method is called multiple times, if the image is changed within the same div which is not a desired behaviour.

**Comment by sandstrom** [comment]
I'm going to close this issue. Happy to reopen if anyone wants to submit a PR.
