### ISSUE TITLE
Images and text appear blurred

### ISSUE THREAD

**Issue by creativesplash** [manuelstofer/pinchzoom#65]
Hello there!

Thanks once again for this fantastic plugin! My images and text appear blurred when I zoom in. Any ideas what could be happening?

Thanks,
Vasanth

**Comment by sandstrom** [comment]
No idea 😄 

This is open source code, unfortunately we cannot offer general troubleshooting. But if you think you've found a bug, and a way to fix it, we're happy to accept a PR with a fix.

A simple reproduction or the issue is usually a good start.

**Comment by sandstrom** [comment]
I'm going to close this issue. Happy to review a PR if anyone has found a reproducible bug.
