### ISSUE TITLE
In `src/pinch-zoom.js`, please change `const` keyword to `var` in function `getCurrentZoomCenter`

### ISSUE THREAD

**Issue by levblanc** [manuelstofer/pinchzoom#68]
Would you please change the `const` keyword to `var` in `src/pinch-zoom.js`?

![image](https://user-images.githubusercontent.com/4057887/44707437-16158600-aad7-11e8-983b-6807376e499c.png)

It triggers error in low version browsers:

```
Const declarations are not supported in strict mode
```

Function `getCurrentZoomCenter` is the only place that has the `const` keyword. In other functions of `src/pinch-zoom.js`, and the whole `dist/pinch-zoom.umd.js`, you are using `var` consistently.  

### Reason of the error:

In your `package.json`, `module` field is set to `src/pinch-zoom.js`. 

so when we import your plugin-in like so:

```javascript
import PinchZoom from 'pinch-zoom-js';
```

we are importing `src/pinch-zoom.js`, which has the `const` keyword.

If in our project's webpack setting, we exclude `node_modules` (which seems to be default settings of webpack) like so:

```javascript
{
    test: /\.js$/,
    loader: 'babel-loader',
    exclude: /node_modules/
}
```
or so:

```javascript
{
    test: /\.js$/,
    loader: 'babel-loader',
    include: [
        resolve('src')
    ]
}
```

webpack will not compile `src/pinch-zoom.js` in `node_modules`, and lead to the error.

Although including `node_modules/pinch-zoom-js` in webpack settings manually when coming across this problem is a workaround, modifying from the source will save the world in one shot. :)

**Comment by sandstrom** [comment]
@levblanc Thanks for chiming in! 💯 

Happy to change this, would you like to submit a PR?

**Comment by levblanc** [comment]
@sandstrom 
Opened PR #69 , please check. :)

**Comment by zyniq82** [comment]
@levblanc & @sandstrom, isn't the real problem that the `module` field in `package.json` is referencing `src/pinch-zoom.js`, instead of `dist/pinch-zoom.umd.js`? (since that line in `package.json` was written before the `dist/` folder was part of the repository)

The build script is using Babel to simplify the code in `src/`, such that "low version browsers" can use whatever is created in `dist/`, regardless of how modern the code was that was written in `src/`.

**Comment by sandstrom** [comment]
@levblanc Fixed!

**Comment by cslee** [comment]
@sandstrom Can you please release an updated version of the npm package on this? Thanks.

**Comment by sandstrom** [comment]
@cslee Fixed
