### ISSUE TITLE
Create multi TouchEvents programmatically to zoom 

### ISSUE THREAD

**Issue by AllenBootung** [manuelstofer/pinchzoom#72]
My device using TUIO, not mobile touch, so I have to create touch events programmatically to trigger pinch-zoom.umd.js
https://jsbin.com/baginicari/edit?js,console,output

I have tried
`myElement = document.querySelector('#g2');`
`sendTouchEvent(247, 379, myElement, 'touchstart');`
`sendTouchEvent(317, 591, myElement, 'touchstart');`

`sendTouchEvent(257, 389, myElement, 'touchmove');`
`sendTouchEvent(307, 581, myElement, 'touchmove');`

`sendTouchEvent(267, 399, myElement, 'touchmove');`
`sendTouchEvent(297, 571, myElement, 'touchmove');`

but the touchList never exceed 1. Pictures can move but can't zoom.
Can somebody help?

`function sendTouchEvent(x, y, element, eventType) {`
`　　const touchObj = new Touch({`
`　　　identifier: Date.now(),`
`　　　target: element,`
`　　　clientX: x,`
`　　　clientY: y,`
`　　　pageX: x,`
`　　　pageY: y,`
`　　　screenX: x,`
`　　　screenY: y,`
`　　　radiusX: 2.5,`
`　　　radiusY: 2.5,`
`　　　rotationAngle: 0,`
`　　　force: 0.5,`
`　　});`
`  `
`　　const touchEvent = new TouchEvent(eventType, {`
`　　　　cancelable: true,`
`　　　　bubbles: true,`
`　　　　touches: [touchObj],`
`　　　　targetTouches: [],`
`　　　　changedTouches: [touchObj]`
`　　`
`　　});`

`　　element.dispatchEvent(touchEvent);`
`}`

**Comment by sandstrom** [comment]
Hi @AllenBootung! 

This is a small, community supported plugin, so we cannot offer support for it.

If you have found any bug and a fix for them, I'm happy to review a PR.

Have a great weekend! ⛵️
