### ISSUE TITLE
How to zoom using method?

### ISSUE THREAD

**Issue by achigo16** [manuelstofer/pinchzoom#79]
like method to enable and disable gesture, 
```js
let pz = new PinchZoom(myElement);

pz.enable(); // Enables all gesture capturing (is enabled by default)
pz.disable(); // Disables all gesture capturing
```
it is there way to zoom using method?

**Comment by sandstrom** [comment]
@achigo16 It's currently built to handle support via user interaction. There is no programmatic access to zoom.

I'm going to close this issue now.

Maybe we can accept a PR adding this functionality. But if you are interested in patching this into the library it would be great if we could discuss some details first (before you'd start to code it).

**Comment by williammustaffa** [comment]
A way to do that is to extend the PinchZoom class:
```
    // Get container's center
    PinchZoom.prototype.getContainerCenter = function () {
      var centerX = this.container.offsetLeft + this.container.offsetWidth / 2;
      var centerY = this.container.offsetTop + this.container.offsetHeight / 2;

      return {
        x: centerX,
        y: centerY,
      };
    };

    // Create method to zoom to target zoom factor
    PinchZoom.prototype.zoomTo = function (zoomFactor) {
      var center = this.getContainerCenter();
      var startZoomFactor = this.zoomFactor;
      var updateProgress = (function (progress) {
        this.scaleTo(startZoomFactor + progress * (zoomFactor - startZoomFactor), center);
      }).bind(this);

      this.animate(this.options.animationDuration, updateProgress, this.swing);
    }

    // Zoom In (factor 2)
    PinchZoom.prototype.zoomIn = function () {
      this.zoomTo(2);
    };
    
    // Zoom out (factor 1)
    PinchZoom.prototype.zoomOut = function () {
      this.zoomTo(1);
    };
```

**Comment by michael-ts** [comment]
@sandstrom Not the original submitter, but before I code *what* exactly?

I need to be able to zoom/pan on the object from a desktop browser as well.  I assume it's up to me to write whatever code I want to handle this, whether it's a bottom or a mouse event.

When this happens, I need some way to manipulate the object in javascript the same as your code is doing.  How do I do this?

**Comment by michael-ts** [comment]
@sandstrom 

Ok, so I have watched activity when I pinch-zoom.  I see `handleZoom` get called when I am pinching, and this in turn calls `scale`.  I made a note of the exact parameters being passed to scale and then call it the same identical way when a button is clicked in my app - but **nothing happens**.

What am I doing wrong?

**Comment by michael-ts** [comment]
So apparently after calling `scale` I have to then call `update`.  But I'm not sure what to pass as the second (center) parameter to `scale`.  I thought to call `getCurrentZoomCenter` to find out, but it returns `null` for both x and y until the UI has actually been touched, apparently, which isn't helpful if there is no touch surface.

**Comment by michael-ts** [comment]
Trying to figure out what to pass as the center parameter is ridiculous!

**Comment by sandstrom** [comment]
@michael-ts I can hear that you're frustrated. I actually didn't build this library, so I don't know it's inner workings that well (though I have poked around the code a bit).

Thanks for thinking about how this project can be improved! Since this code is open-source, without anyone getting paid to work on it, it's difficult to satisfy all the wishes that people may have. I hope you understand! 🌻 

So if you want something, a good first step is to explain in detail what you think should be changed. If others agree that it's a good idea, the next step would be for you to open a PR with the necessary code changes.

**Comment by williammustaffa** [comment]
Hello @michael-ts,

I've already had this issue and I've extended the plugin to have more methods not touch based.
[PinchZoomExtended.js - Gist](https://gist.github.com/williammustaffa/c68137762359bac7e9196a9b02be9471)
Above is the solution I could think of.
Extending it you could use the new methods `pz.zoomTo(zoomFactor)`, `pz.zoomIn()`, `pz.zoomOut()` and `pz.getContainerCenter()` which will give the current center coordinates of the container element.

I hope it helps. :)

**Comment by michael-ts** [comment]
@williammustaffa Awesome, thanks for the link!  It's not quite working for me though, in my desktop browser it shifts the element off to the right and slightly down, whereas on mobile it shifts it down and slightly to the right.  I'm going to keep playing with it until I get it right and then I'll share what worked for me.

@sandstrom Thank you for the kind words.   The main frustration I was having was with the documentation.  It seems all too common that people hide behind the excuse of it being open source to not provide decent documentation - often a few minutes by the author to write down what they were thinking can save many hours of unnecessary detective work down the line. The documentation for this project is actually quite adequate except for the corner case of wanting to control the pinch zoom via non-touch means.  I've never actually had the time to figure out the details of how a PR works and use it (I read the docs a couple times but have mostly forgotten now) but I'll be happy to share what works for me and then decide where to go from there.
