### ISSUE TITLE
Can you add support on pc mouse drag and zoom?

### ISSUE THREAD

**Issue by mask2012** [manuelstofer/pinchzoom#80]
as I'm working on pc, I can not get pz_zoomstart  feedback information easily~
can you add support  for mouse drag and zoom?

**Comment by sandstrom** [comment]
No immediate plans. But happy to review a PR.

**Comment by sandstrom** [comment]
Closing for now. If you want to help implement this I'm happy to discuss details further

**Comment by retyui** [comment]
I created a module for the react where I added support Mouse and Wheel events

[react-quick-pinch-zoom](https://github.com/retyui/react-quick-pinch-zoom)
