### ISSUE TITLE
pinch-zoom-container getting height 0px

### ISSUE THREAD

**Issue by rooby** [manuelstofer/pinchzoom#9]
After I attach pinch zoom to my element (a div with an image and text inside) the pinch zoom container gets this markup:

```
<div class="pinch-zoom-container" style="overflow: hidden; position: relative; height: 0px;">
```

and I cannot see my image.

If I manually change the height to something like 700px then the image is visible.

Any ideas of what might be the problem?

**Comment by sandstrom** [comment]
Fixed in https://github.com/manuelstofer/pinchzoom/commit/3cfdd4291650bb01270f2fbc2fe7217a68255d98
