### ISSUE TITLE
Unable to run the callbacks in v 2.3.2

### ISSUE THREAD

**Issue by gonzalle** [manuelstofer/pinchzoom#94]
I even don't see the documented callbacks in the code (eg. `onZoomStart`).
Am I doing something wrong ?
Maybe you should update the demo files with the new version and a few callbacks.

Thxs

**Comment by gonzalle** [comment]
The callbacks are not in  : dist/pinch-zoom.umd.js , but are in the minified version. as in file in src.
If I use one of those file I got an error : `Uncaught SyntaxError: Unexpected token export`

**Comment by sandstrom** [comment]
@gonzalle Would you like to PR a fix?

**Comment by gonzalle** [comment]
I have no fix to PR.
I'm not familiar with modules, this is the reason I didn't use pinch-zoom the right way.
I can only suggest to provide a working demo that uses the last release. Obviously the src and the dist don't work the same way.
