### ISSUE TITLE
A special situation

### ISSUE THREAD

**Issue by azhi268** [manuelstofer/pinchzoom#96]
Hello,dear writer
I find there is a special situation that I can't solve,so I come for some help.
![image](https://user-images.githubusercontent.com/31687938/57769416-681f3a00-7740-11e9-87f1-45f7d864d18c.png)

I give the swiper_box Classname，but when i switch the swiper ,it's still the same Big size, do we have a way to resize that?

**Comment by sandstrom** [comment]
Is this an issue with the code itself, or a general question? For general questions [Stackoverflow](https://stackoverflow.com/) is better than Github.

I'm closing this now, but I'm willing to reopen if there is an actual code issue. If so, steps to reproduce (and ideally a failing test-case) is a good start.
